#!/usr/bin/osascript -l JavaScript
// Enpass for Alfred — search an Enpass vault and copy passwords, usernames and one-time codes.
// Reads the vault through enpass-cli (https://github.com/hazcod/enpass-cli); never writes to it.
//
// Usage: ./enpass.js <mode> [argument]
//   list [query]     Script Filter: vault entries (no secrets are loaded)
//   fields [query]   Script Filter: fields of the entry in $entry_uuid
//   act [input]      Action: runs $action for $entry_uuid (copy, paste, open, set password…)
//   clear <count>    Internal: clear the clipboard if it still holds what we copied

ObjC.import("Foundation")
ObjC.import("AppKit")

const DEFAULT_BUNDLE_ID = "com.x-o-r-r-o.alfred.enpass"
const DEFAULT_VAULT = "~/Library/Containers/in.sinew.Enpass-Desktop/Data/Documents/Vaults/primary"
const ENPASS_BUNDLE_ID = "in.sinew.Enpass-Desktop"
const DEFAULT_CLI_CANDIDATES = ["/opt/homebrew/bin/enpass-cli", "/usr/local/bin/enpass-cli"]
const MASK = "••••••••"
const SEP = " · "

// Pasteboard types that tell clipboard managers (including Alfred's Clipboard History) to skip the copy
// See http://nspasteboard.org
const PRIVATE_PASTEBOARD_TYPES = [
  "org.nspasteboard.ConcealedType",
  "org.nspasteboard.TransientType",
  "org.nspasteboard.AutoGeneratedType",
]

// Field types Enpass stores without a label
const TYPE_LABELS = {
  username: "Username",
  email: "Email",
  password: "Password",
  url: "Website",
  totp: "One-time code",
  phone: "Phone",
  pin: "PIN",
  ccName: "Cardholder",
  ccNumber: "Card number",
  ccCvc: "Security code",
  ccExpiry: "Expiry date",
  ccPin: "Card PIN",
  ccType: "Card type",
  ccValidFrom: "Valid from",
  ccBankname: "Bank",
  ccTxnpassword: "Transaction password",
  date: "Date",
  multiline: "Note",
  text: "Text",
}

// Field types that are always masked and never used for matching, even if Enpass doesn't flag them
const SECRET_TYPES = new Set(["password", "totp", "pin", "ccNumber", "ccCvc", "ccPin", "ccTxnpassword"])

// Enpass categories → icon file in icons/
const CATEGORY_ICONS = {
  login: "login",
  password: "password",
  creditcard: "creditcard",
  finance: "finance",
  note: "note",
  identity: "identity",
  license: "note",
  travel: "identity",
  computer: "wifi",
  wifi: "wifi",
  misc: "login",
}

// ─── Environment ────────────────────────────────────────────────────────────

function envVar(name, fallback = "") {
  const value = $.NSProcessInfo.processInfo.environment.objectForKey(name).js
  return value === undefined || value === "" ? fallback : value
}

function expandHome(path) {
  if (path === "~") return $.NSHomeDirectory().js
  if (path.startsWith("~/")) return $.NSHomeDirectory().js + path.slice(1)
  return path
}

const config = {
  keyword: envVar("keyword", "enp").trim(),
  vaultPath: expandHome(envVar("vault_path", DEFAULT_VAULT).trim()).replace(/\/+$/, ""),
  keyfilePath: expandHome(envVar("keyfile_path", "").trim()),
  cliPath: expandHome(envVar("enpass_cli", "").trim()),
  defaultAction: envVar("default_action", "copy") === "paste" ? "paste" : "copy",
  clearAfter: Math.max(0, parseInt(envVar("clear_after", "30"), 10) || 0),
  showTrashed: envVar("show_trashed", "0") === "1",
  bundleId: envVar("alfred_workflow_bundleid", DEFAULT_BUNDLE_ID),
  // Test hooks (test/run.sh): a separate Keychain service, and in dry-run mode no pasting, opening,
  // Alfred scripting or dialogs (the dialog answer comes from enpass_test_answer)
  keychainService: envVar("enpass_keychain_service", ""),
  dryRun: envVar("enpass_dry_run", "0") === "1",
}
// Seconds before a stuck enpass-cli is stopped
const CLI_TIMEOUT = config.dryRun && envVar("enpass_test_timeout") ? Number(envVar("enpass_test_timeout")) : 30
const CLI_CANDIDATES = config.dryRun && envVar("enpass_test_candidates")
  ? envVar("enpass_test_candidates").split(":")
  : DEFAULT_CLI_CANDIDATES

// ─── Processes ──────────────────────────────────────────────────────────────

// Runs an executable with an argument array (no shell). Extra environment variables are only
// visible to the child process. Returns { status, out, err }.
function exec(path, args, { input, env, timeout } = {}) {
  const task = $.NSTask.alloc.init
  task.executableURL = $.NSURL.fileURLWithPath(path)
  task.arguments = $(args)
  if (env) {
    const merged = $.NSMutableDictionary.dictionaryWithDictionary($.NSProcessInfo.processInfo.environment)
    for (const key of Object.keys(env)) merged.setObjectForKey($(env[key]), $(key))
    task.environment = merged
  }
  const stdin = $.NSPipe.pipe
  const stdout = $.NSPipe.pipe
  // stderr goes to a private temporary file, so a large error output can't fill a pipe and
  // block the child while stdout is being read. It only ever holds error messages.
  const fm = $.NSFileManager.defaultManager
  const errPath = $.NSTemporaryDirectory().js + "enpass-alfred-" + $.NSUUID.UUID.UUIDString.js + ".err"
  fm.createFileAtPathContentsAttributes(errPath, $(), $({ NSFilePosixPermissions: 0o600 }))
  const errHandle = $.NSFileHandle.fileHandleForWritingAtPath(errPath)
  task.standardInput = stdin
  task.standardOutput = stdout
  task.standardError = errHandle.isNil() ? $.NSFileHandle.fileHandleWithNullDevice : errHandle
  const error = Ref()
  if (!task.launchAndReturnError(error)) {
    fm.removeItemAtPathError(errPath, null)
    const reason = error[0] && !error[0].isNil() ? error[0].localizedDescription.js : ""
    return { status: -1, out: "", err: reason || "Could not start " + path }
  }
  // Watchdog: stops the child and anything it started (its process group) if it runs too long,
  // since reading stdout below blocks until every process holding the pipe has exited
  let watchdog = null
  if (timeout) {
    watchdog = $.NSTask.alloc.init
    watchdog.executableURL = $.NSURL.fileURLWithPath("/bin/sh")
    // On TERM (child finished in time) it also stops its sleep, so nothing is left running
    watchdog.arguments = $(["-c", 'trap \'kill "$s" 2>/dev/null; exit 0\' TERM; sleep "$1" & s=$!; wait "$s" && { kill -9 -- "-$2" || kill -9 "$2"; } 2>/dev/null',
      "sh", String(timeout), String(task.processIdentifier)])
    watchdog.standardOutput = $.NSFileHandle.fileHandleWithNullDevice
    watchdog.standardError = $.NSFileHandle.fileHandleWithNullDevice
    if (!watchdog.launchAndReturnError(Ref())) watchdog = null
  }
  if (input !== undefined) stdin.fileHandleForWriting.writeData($(input).dataUsingEncoding($.NSUTF8StringEncoding))
  stdin.fileHandleForWriting.closeFile
  const outData = stdout.fileHandleForReading.readDataToEndOfFile
  task.waitUntilExit
  if (watchdog && watchdog.running) watchdog.terminate
  const timedOut = Boolean(timeout) && task.terminationReason === $.NSTaskTerminationReasonUncaughtSignal && task.terminationStatus === 9
  if (!errHandle.isNil()) errHandle.closeFile
  const errData = $.NSData.dataWithContentsOfFile(errPath)
  fm.removeItemAtPathError(errPath, null)
  return {
    status: task.terminationStatus,
    timedOut,
    out: timedOut ? "" : $.NSString.alloc.initWithDataEncoding(outData, $.NSUTF8StringEncoding).js || "",
    err: errData.isNil() ? "" : $.NSString.alloc.initWithDataEncoding(errData, $.NSUTF8StringEncoding).js || "",
  }
}

function fileExists(path, directory = false) {
  const isDir = Ref()
  const exists = $.NSFileManager.defaultManager.fileExistsAtPathIsDirectory(path, isDir)
  return exists && Boolean(isDir[0]) === directory
}

function isExecutable(path) {
  return fileExists(path) && $.NSFileManager.defaultManager.isExecutableFileAtPath(path)
}

function findCli() {
  if (config.cliPath) return isExecutable(config.cliPath) ? config.cliPath : null
  const pathDirs = config.dryRun && envVar("enpass_test_candidates") ? [] : envVar("PATH", "").split(":").filter(Boolean).map((dir) => dir + "/enpass-cli")
  return [...CLI_CANDIDATES, ...pathDirs].find(isExecutable) || null
}

// ─── Errors ─────────────────────────────────────────────────────────────────

class SetupError extends Error {
  // kind picks the icon and action of the row shown in Alfred
  constructor(kind, title, subtitle, extra = {}) {
    super(title)
    this.kind = kind
    this.subtitle = subtitle
    this.extra = extra
  }
}

// ─── Vault ──────────────────────────────────────────────────────────────────

function readJSON(path) {
  const data = $.NSData.dataWithContentsOfFile(path)
  if (data.isNil()) return null
  try {
    return JSON.parse($.NSString.alloc.initWithDataEncoding(data, $.NSUTF8StringEncoding).js)
  } catch (e) {
    return null
  }
}

function loadVault() {
  const cli = findCli()
  if (!cli) {
    if (config.cliPath) {
      throw new SetupError("config", "enpass-cli not found at the configured path",
        config.cliPath + " — fix it in the Workflow’s Configuration")
    }
    throw new SetupError("install", "Install enpass-cli to use this workflow",
      "↩ Copy the install command: brew install enpass-cli")
  }
  if (!fileExists(config.vaultPath, true)) {
    throw new SetupError("config", "Enpass vault folder not found",
      config.vaultPath + " — set it in the Workflow’s Configuration")
  }
  const info = readJSON(config.vaultPath + "/vault.json")
  if (!info || !fileExists(config.vaultPath + "/vault.enpassdb")) {
    throw new SetupError("config", "Not an Enpass vault folder",
      "Expected vault.json and vault.enpassdb in " + config.vaultPath)
  }
  const needsKeyfile = Number(info.have_keyfile) === 1
  if (needsKeyfile && !config.keyfilePath) {
    throw new SetupError("config", "This vault needs a keyfile",
      "Choose your Enpass keyfile in the Workflow’s Configuration")
  }
  if (needsKeyfile && !fileExists(config.keyfilePath)) {
    throw new SetupError("config", "Keyfile not found", config.keyfilePath)
  }
  return {
    cli,
    name: String(info.vault_name || "Enpass"),
    account: String(info.vault_uuid || config.vaultPath),
    // enpass-cli refuses a keyfile the vault doesn't use, so only pass it when needed
    keyfile: needsKeyfile ? config.keyfilePath : "",
  }
}

function cliArgs(vault, command, filters = []) {
  const args = ["-vault", config.vaultPath]
  if (vault.keyfile) args.push("-keyfile", vault.keyfile)
  args.push("-nonInteractive", "-log", "error", "-json", "-detailed")
  if (config.showTrashed) args.push("-trashed")
  // Filters are positional; flag parsing stops at the command, so filters starting with "-" are safe
  return [...args, command, ...filters]
}

// Runs enpass-cli with the master password in its environment and returns the parsed entries
function runCli(vault, password, command, filters = []) {
  const result = exec(vault.cli, cliArgs(vault, command, filters), { env: { MASTERPW: password }, timeout: CLI_TIMEOUT })
  if (result.timedOut) throw new SetupError("error", "enpass-cli took too long", "Try again, or check that the vault isn’t locked by another app")
  if (result.status === 0) {
    try {
      const entries = JSON.parse(result.out || "[]")
      if (!Array.isArray(entries)) return []
      // Normalise what the rest of the script relies on
      return entries.filter((e) => e && typeof e.uuid === "string").map((e) => ({
        ...e,
        title: String(e.title || ""),
        subtitle: String(e.subtitle || ""),
        fields: (Array.isArray(e.fields) ? e.fields : []).map((f) => ({ ...f, type: String(f.type || "text"), label: String(f.label || ""), value: f.value === undefined ? undefined : String(f.value) })),
      }))
    } catch (e) {
      throw new SetupError("error", "Unexpected output from enpass-cli", "Try updating it: brew upgrade enpass-cli")
    }
  }
  throw cliError(result)
}

// Turns an enpass-cli failure into a row that tells the user what to do. Never includes secrets.
function cliError(result) {
  const message = (result.err.match(/msg="([^"]*)"/) || [])[1] || result.err.trim().split("\n").pop() || ""
  const detail = (result.err.match(/error="([^"]*)"/) || [])[1] || ""
  const text = (message + " " + detail).toLowerCase()
  if (text.includes("could not open vault") || text.includes("file is not a database") || text.includes("could not generate database key")) {
    if (text.includes("keyfile")) {
      return new SetupError("config", "Could not read the keyfile", detail || message)
    }
    return new SetupError("badpassword", "Wrong master password or keyfile",
      "↩ Enter the master password again")
  }
  if (text.includes("keyfile")) return new SetupError("config", "Keyfile problem", detail || message)
  return new SetupError("error", "enpass-cli failed", (message + (detail ? ": " + detail : "")).trim() || "Exit code " + result.status)
}

// ─── Keychain ───────────────────────────────────────────────────────────────
// The master password is stored base64-encoded (security -w hex-encodes non-ASCII values),
// written through `security -i` on stdin so it never appears in a process list.

function keychainService() {
  return config.keychainService || config.bundleId
}

function base64Encode(text) {
  return $(text).dataUsingEncoding($.NSUTF8StringEncoding).base64EncodedStringWithOptions(0).js
}

function base64Decode(text) {
  const data = $.NSData.alloc.initWithBase64EncodedStringOptions($(text.trim()), 0)
  if (data.isNil()) return null
  return $.NSString.alloc.initWithDataEncoding(data, $.NSUTF8StringEncoding).js ?? null
}

function quoteForSecurity(text) {
  // A newline would end the `security -i` command line and start another, so drop control characters
  const clean = String(text).replace(/[\u0000-\u001f\u007f]/g, " ")
  return '"' + clean.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"'
}

function getPassword(vault) {
  const result = exec("/usr/bin/security", ["find-generic-password", "-s", keychainService(), "-a", vault.account, "-w"])
  if (result.status === 44) return null // not found
  if (result.status !== 0) {
    throw new SetupError("error", "Could not read the master password from the Keychain",
      "Allow access when macOS asks, or unlock your login keychain")
  }
  const password = base64Decode(result.out)
  if (password === null) throw new SetupError("badpassword", "Stored master password is unreadable", "↩ Enter it again")
  return password
}

function savePassword(vault, password) {
  const label = "Enpass for Alfred (" + vault.name.slice(0, 80) + ")"
  const command = ["add-generic-password", "-U",
    "-s", quoteForSecurity(keychainService()),
    "-a", quoteForSecurity(vault.account),
    "-l", quoteForSecurity(label),
    "-j", quoteForSecurity("Master password for the Enpass vault, base64-encoded"),
    "-w", quoteForSecurity(base64Encode(password))].join(" ")
  const result = exec("/usr/bin/security", ["-i"], { input: command + "\n" })
  // security -i exits 0 even when a command fails, so read the password back to confirm
  return result.status === 0 && getPassword(vault) === password
}

function deletePassword(vault) {
  const result = exec("/usr/bin/security", ["delete-generic-password", "-s", keychainService(), "-a", vault.account])
  return result.status === 0
}

// Returns the vault and a working master password, or throws a SetupError
function unlock() {
  const vault = loadVault()
  const password = getPassword(vault)
  if (password === null) {
    throw new SetupError("setpassword", "Unlock " + vault.name + " vault",
      "↩ Enter your Enpass master password (saved in your macOS Keychain)")
  }
  return { vault, password }
}

// ─── Entry helpers ──────────────────────────────────────────────────────────

function isSecret(field) {
  return Boolean(field.sensitive) || SECRET_TYPES.has(field.type)
}

function fieldLabel(field) {
  if (field.label && field.label.trim()) return field.label.trim()
  return TYPE_LABELS[field.type] || field.type.charAt(0).toUpperCase() + field.type.slice(1)
}

function usernameOf(entry) {
  const field = entry.fields.find((f) => f.type === "username" && f.value)
    || entry.fields.find((f) => f.type === "email" && f.value)
  return field ? field.value : ""
}

// The field ↩ copies: the first password, otherwise the first sensitive field (e.g. a card number)
function isMetadata(field) {
  return field.type.startsWith(".")
}

function primaryFieldIndex(entry) {
  const password = entry.fields.findIndex((f) => f.type === "password")
  if (password >= 0) return password
  return entry.fields.findIndex((f) => isSecret(f) && f.type !== "totp" && !isMetadata(f))
}

function totpFieldIndex(entry) {
  return entry.fields.findIndex((f) => f.type === "totp")
}

function urlOf(entry) {
  const field = entry.fields.find((f) => f.type === "url" && normalizeURL(f.value || ""))
  return field ? normalizeURL(field.value) : ""
}

// Web address to open, or "" when the value isn't one. Other schemes (file://, smb://, app links)
// are never opened: imported or shared vault data shouldn't be able to launch apps or mount shares.
function normalizeURL(value) {
  const url = value.trim()
  if (!url || /\s/.test(url)) return ""
  if (/^https?:\/\//i.test(url)) return url
  if (/^[a-z][a-z0-9+.-]*:/i.test(url) && !/^[^:/]+:\d+(\/|$)/.test(url)) return ""
  return "https://" + url
}

// For display only: scheme, host and path, without a login ("user:pass@") or query string
function displayURL(url) {
  const match = url.match(/^([a-z][a-z0-9+.-]*:\/\/)(?:[^@/?#]*@)?([^?#]*)/i)
  return match ? match[1] + match[2] : ""
}

function hasCredentials(url) {
  return /^[a-z][a-z0-9+.-]*:\/\/[^/?#]*@/i.test(url)
}

function hostOf(url) {
  const match = url.match(/^[a-z][a-z0-9+.-]*:\/\/([^/?#:]+)/i)
  return match ? match[1].replace(/^www\./i, "") : ""
}

function categoryName(category) {
  if (!category) return ""
  const names = { creditcard: "Credit Card", wifi: "Wi-Fi", misc: "Miscellaneous" }
  return names[category.toLowerCase()] || category.charAt(0).toUpperCase() + category.slice(1)
}

function categoryIcon(category) {
  return "icons/" + (CATEGORY_ICONS[(category || "").toLowerCase()] || "login") + ".png"
}

function actionVerb(mode) {
  return mode === "paste" ? "Paste" : "Copy"
}

function otherMode(mode) {
  return mode === "paste" ? "copy" : "paste"
}

// enpass-cli matches filters case-insensitively against title and username with SQLite's lower(),
// which only folds ASCII. So filter on the longest plain ASCII word, e.g. "Bank" from "Bank of Ümlaut 🏦".
// Characters SQLite's lower() and enpass-cli's Go lowercasing agree on: ASCII, and characters without
// case (digits, CJK, emoji…). Returns the longest run of them, e.g. "mlaut 🏦" from "Bank of Ümlaut 🏦".
function filterTerm(text) {
  const runs = Array.from(text || "")
    .map((c) => (c.charCodeAt(0) < 128 || c.toLowerCase() === c.toUpperCase() ? c : "\n"))
    .join("")
    .split("\n")
    .map((run) => run.trim())
    .filter(Boolean)
  return runs.sort((a, b) => b.length - a.length)[0] || ""
}

// Finds an entry by UUID while decrypting as little as possible: `show` (which decrypts secrets)
// only ever runs with a filter, unless the entry has no plain ASCII word in its title or username.
function findEntry(vault, password, uuid, title, command) {
  const found = (entries) => entries.find((e) => e.uuid === uuid)
  const tried = new Set()
  const attempt = (term) => {
    if (!term || tried.has(term.toLowerCase())) return null
    tried.add(term.toLowerCase())
    return found(runCli(vault, password, command, [term]))
  }
  let entry = attempt(filterTerm(title))
  if (!entry) {
    // Look the entry up without secrets to learn its current title and username (it may have been renamed)
    const listed = found(runCli(vault, password, "list"))
    if (!listed) throw new SetupError("error", "Entry not found", "It may have been deleted or renamed in Enpass")
    listed.fields = listed.fields || []
    if (command === "list") entry = listed
    else entry = attempt(filterTerm(listed.title)) || attempt(filterTerm(usernameOf(listed)))
    // Never decrypt the whole vault to find one entry
    if (!entry) throw new SetupError("error", "Can’t read this entry from Alfred",
      "Its title and username can’t be searched by enpass-cli. Copy it in Enpass, or add a plain word to its title")
  }
  if (!entry) throw new SetupError("error", "Entry not found", "It may have been deleted or renamed in Enpass")
  entry.fields = entry.fields || []
  return entry
}

// ─── Script Filter: entries ─────────────────────────────────────────────────

function entryItem(entry) {
  const username = usernameOf(entry)
  const url = urlOf(entry)
  const primary = primaryFieldIndex(entry)
  const totp = totpFieldIndex(entry)
  const title = entry.title || "(untitled)"
  const base = { entry_uuid: entry.uuid, entry_title: entry.title || "" }
  const mode = config.defaultAction
  const primaryLabel = primary >= 0 ? fieldLabel(entry.fields[primary]).toLowerCase() : ""
  const fieldVars = (index) => ({ action: "field", field_index: String(index), field_type: entry.fields[index].type, field_label: fieldLabel(entry.fields[index]), field_secret: isSecret(entry.fields[index]) ? "1" : "0" })
  // Enpass's own subtitle (e.g. "•••• 4242" for cards) when there's no username
  const subtitleParts = [username || (entry.subtitle || "").trim(), categoryName(entry.category)].filter(Boolean)
  if (entry.trashed) subtitleParts.unshift("In Trash")
  const hosts = entry.fields.filter((f) => f.type === "url" && f.value).map((f) => hostOf(normalizeURL(f.value))).filter(Boolean)

  const item = {
    uid: entry.uuid,
    title,
    subtitle: subtitleParts.join(SEP),
    arg: entry.uuid,
    match: [title, username, categoryName(entry.category), ...hosts].filter(Boolean).join(" "),
    autocomplete: title,
    icon: { path: entry.trashed ? "icons/trash.png" : categoryIcon(entry.category) },
    text: { copy: username || title, largetype: title },
    variables: primary >= 0
      ? { ...base, ...fieldVars(primary), mode }
      : { ...base, action: "fields" },
    mods: {
      cmd: username
        ? { valid: true, subtitle: actionVerb(mode) + " username: " + username, variables: { ...base, action: "username", mode } }
        : { valid: false, subtitle: "No username" },
      alt: totp >= 0
        ? { valid: true, subtitle: actionVerb(mode) + " one-time code", variables: { ...base, ...fieldVars(totp), mode } }
        : { valid: false, subtitle: "No one-time code" },
      ctrl: url
        ? { valid: true, subtitle: "Open " + displayURL(url), arg: url, variables: { ...base, action: "url" } }
        : { valid: false, subtitle: "No website" },
      shift: { valid: true, subtitle: "Show all fields", variables: { ...base, action: "fields" } },
      fn: primary >= 0
        ? { valid: true, subtitle: actionVerb(otherMode(mode)) + " " + primaryLabel, variables: { ...base, ...fieldVars(primary), mode: otherMode(mode) } }
        : { valid: false, subtitle: "Nothing to " + actionVerb(otherMode(mode)).toLowerCase() },
    },
  }
  if (primary < 0) item.subtitle = [item.subtitle, "↩ Show fields"].filter(Boolean).join(SEP)
  if (url && !hasCredentials(url)) item.quicklookurl = url
  return item
}

function utilityItems(vault) {
  const items = [
    {
      title: "Open Enpass",
      subtitle: "Open the Enpass app",
      match: "open enpass app",
      arg: "open_enpass",
      icon: { type: "fileicon", path: "/Applications/Enpass.app" },
      variables: { action: "open_enpass" },
    },
    {
      title: "Workflow Configuration",
      subtitle: "Change the vault, keyfile, keyword and clipboard options",
      match: "settings configuration configure preferences options",
      arg: "configure",
      icon: { path: "icons/settings.png" },
      variables: { action: "configure" },
    },
  ]
  if (vault) {
    items.unshift({
      title: "Forget Master Password",
      subtitle: "Remove it from your Keychain. You’ll be asked for it next time",
      match: "lock forget logout sign out master password keychain",
      arg: "forget",
      icon: { path: "icons/lock.png" },
      variables: { action: "forget" },
    })
  }
  return items
}

function setupItem(error) {
  const icons = { install: "warning", config: "settings", setpassword: "unlock", badpassword: "lock", error: "warning" }
  const item = {
    title: error.message,
    subtitle: error.subtitle || "",
    valid: false,
    icon: { path: "icons/" + (icons[error.kind] || "warning") + ".png" },
  }
  if (error.kind === "install") {
    Object.assign(item, { valid: true, arg: "brew install enpass-cli", variables: { action: "copy_text", text: "brew install enpass-cli" } })
  } else if (error.kind === "config") {
    Object.assign(item, { valid: true, arg: "configure", variables: { action: "configure" } })
    item.subtitle = item.subtitle ? item.subtitle : "↩ Open the Workflow’s Configuration"
  } else if (error.kind === "setpassword" || error.kind === "badpassword") {
    Object.assign(item, { valid: true, arg: "setpassword", variables: { action: "setpassword" } })
  }
  return item
}

function listEntries() {
  let vault = null
  try {
    const unlocked = unlock()
    vault = unlocked.vault
    const entries = runCli(vault, unlocked.password, "list")
    const items = entries
      .map((entry) => ({ ...entry, fields: entry.fields || [] }))
      .sort((a, b) => (a.title || "").localeCompare(b.title || "", undefined, { sensitivity: "base" })
        || usernameOf(a).localeCompare(usernameOf(b)))
      .map(entryItem)
    if (items.length === 0) {
      items.push({ title: "No entries in " + vault.name, subtitle: "Add items in Enpass", valid: false, icon: { path: "icon.png" } })
    }
    return {
      items: [...items, ...utilityItems(vault)],
      // Alfred keeps these rows (titles, usernames, websites; never secrets) in memory for a minute
      cache: { seconds: 60, loosereload: true },
    }
  } catch (error) {
    if (!(error instanceof SetupError)) throw error
    if (error.kind === "badpassword") {
      // Recover the vault so "Forget Master Password" stays available
      try { vault = loadVault() } catch (e) { vault = null }
    }
    return { skipknowledge: true, items: [setupItem(error), ...utilityItems(vault)] }
  }
}

// ─── Script Filter: fields of one entry ─────────────────────────────────────

function listFields() {
  const uuid = envVar("entry_uuid")
  const title = envVar("entry_title")
  const back = {
    title: "Back to Search",
    subtitle: "Return to all entries",
    match: "back return search",
    arg: "back",
    icon: { path: "icons/back.png" },
    variables: { action: "back" },
  }
  try {
    const { vault, password } = unlock()
    const entry = findEntry(vault, password, uuid, title, "list")
    const mode = config.defaultAction
    const base = { entry_uuid: uuid, entry_title: title }
    let section = ""
    const items = []
    entry.fields.forEach((field, index) => {
      // Types starting with "." are Enpass's own metadata (linked Android apps, 2FA hints)
      if (isMetadata(field)) return
      if (field.type === "section") {
        section = field.label || ""
        return
      }
      const label = fieldLabel(field)
      const isURL = field.type === "url"
      const secret = isSecret(field)
      const value = secret
        ? (field.type === "totp" ? "Current code" : MASK)
        : isURL && hasCredentials(normalizeURL(field.value || "")) ? displayURL(normalizeURL(field.value))
        : (field.value || "").replace(/\s*\n\s*/g, " ⏎ ")
      const vars = { ...base, action: "field", field_index: String(index), field_type: field.type, field_label: label, field_secret: secret ? "1" : "0" }
      const item = {
        title: label,
        subtitle: [section, value].filter(Boolean).join(" › "),
        arg: String(index),
        match: [label, section, secret ? "" : value, field.type].filter(Boolean).join(" "),
        icon: { path: fieldIcon(field) },
        variables: { ...vars, mode },
        mods: {
          cmd: { valid: true, subtitle: actionVerb(otherMode(mode)) + " " + label.toLowerCase(), variables: { ...vars, mode: otherMode(mode) } },
          ctrl: isURL && normalizeURL(field.value || "")
            ? { valid: true, subtitle: "Open " + displayURL(normalizeURL(field.value)), arg: normalizeURL(field.value), variables: { ...vars, action: "open_field" } }
            : { valid: false, subtitle: "Not a web address" },
        },
      }
      if (!secret && field.value) item.text = { copy: field.value, largetype: field.value }
      items.push(item)
    })
    if (items.length === 0) {
      items.push({ title: "This entry has no fields", subtitle: entry.title, valid: false, icon: { path: "icons/fields.png" } })
    }
    return { skipknowledge: true, items: [...items, back] }
  } catch (error) {
    if (!(error instanceof SetupError)) throw error
    return { skipknowledge: true, items: [setupItem(error), back] }
  }
}

function fieldIcon(field) {
  if (field.type === "totp") return "icons/totp.png"
  if (field.type === "url") return "icons/url.png"
  if (field.type === "username" || field.type === "email") return "icons/username.png"
  if (field.type === "password") return "icons/password.png"
  if (field.type.startsWith("cc")) return "icons/creditcard.png"
  if (isSecret(field)) return "icons/secret.png"
  return "icons/text.png"
}

// ─── Actions ────────────────────────────────────────────────────────────────

// Output for the Run Script: arg becomes the notification text (empty = no notification)
function notify(title, text = "") {
  return JSON.stringify({ alfredworkflow: { arg: text || title, variables: { notif_title: title } } })
}

function silent() {
  return JSON.stringify({ alfredworkflow: { arg: "", variables: { notif_title: "" } } })
}

function writeSecretToClipboard(value) {
  const pasteboard = $.NSPasteboard.generalPasteboard
  // Current host only: keeps secrets off Universal Clipboard (Handoff to other devices)
  pasteboard.prepareForNewContentsWithOptions($.NSPasteboardContentsCurrentHostOnly)
  pasteboard.setStringForType($(value), $.NSPasteboardTypeString)
  for (const type of PRIVATE_PASTEBOARD_TYPES) pasteboard.setStringForType($(""), $(type))
  return Number(pasteboard.changeCount)
}

function pasteIntoFrontmostApp() {
  if (config.dryRun) return
  delay(0.1)
  Application("System Events").keystroke("v", { using: "command down" })
}

// Clears the clipboard later, in a detached process, only if nothing else was copied meanwhile
function scheduleClear(changeCount) {
  if (config.clearAfter <= 0) return
  // Alfred runs scripts from the workflow folder
  const script = $.NSFileManager.defaultManager.currentDirectoryPath.js + "/enpass.js"
  const task = $.NSTask.alloc.init
  task.executableURL = $.NSURL.fileURLWithPath("/bin/sh")
  task.arguments = $(["-c", 'sleep "$1" && exec /usr/bin/osascript -l JavaScript "$2" clear "$3"', "sh",
    String(config.clearAfter), script, String(changeCount)])
  task.standardInput = $.NSFileHandle.fileHandleWithNullDevice
  task.standardOutput = $.NSFileHandle.fileHandleWithNullDevice
  task.standardError = $.NSFileHandle.fileHandleWithNullDevice
  task.launchAndReturnError($())
}

function clearClipboard(expectedCount) {
  const pasteboard = $.NSPasteboard.generalPasteboard
  if (String(pasteboard.changeCount) === String(expectedCount)) pasteboard.clearContents
}

function deliver(value, mode, what) {
  const count = writeSecretToClipboard(value)
  // Schedule clearing first, so the secret doesn't stay on the clipboard if pasting fails
  scheduleClear(count)
  if (mode === "paste") {
    try {
      pasteIntoFrontmostApp()
    } catch (e) {
      return notify("Copied " + what + " but couldn’t paste",
        "Allow Alfred in System Settings → Privacy & Security → Accessibility.")
    }
  }
  const done = mode === "paste" ? "Pasted " : "Copied "
  const clears = config.clearAfter > 0 ? " Clipboard clears in " + config.clearAfter + " s." : ""
  // Entry titles stay out of notifications: Notification Center keeps them and may show them on the lock screen
  return notify(done + what, clears.trim() || "Clipboard won’t be cleared automatically.")
}

function openURL(url) {
  url = normalizeURL(url || "")
  if (!url) return notify("No website to open")
  if (!config.dryRun) {
    const nsurl = $.NSURL.URLWithString($(url))
    if (nsurl.isNil() || !$.NSWorkspace.sharedWorkspace.openURL(nsurl)) return notify("Could not open website", displayURL(url))
  }
  return silent()
}

// Resolves a field by index and checks its type (and label, when known) still match what the row showed
function fieldAt(entry, index, type, label = envVar("field_label")) {
  const field = entry.fields[Number(index)]
  if (!field || (type && field.type !== type) || (label && fieldLabel(field) !== label)) {
    throw new SetupError("error", "Entry changed", "Search again to see its current fields")
  }
  return field
}

// Codes use the standard 30-second period (enpass-cli computes them the same way)
function totpValue(vault, password, uuid, title, index) {
  const windowBefore = Math.floor(Date.now() / 30000)
  let field = fieldAt(findEntry(vault, password, uuid, title, "show"), index, "totp")
  const now = Date.now() / 1000
  const remaining = 30 - now % 30
  // The code may have been computed in a window that has since ended, or be about to expire:
  // wait for the next window if needed and read it again
  if (!field.totp_error && (Math.floor(now / 30) !== windowBefore || remaining <= 3)) {
    if (remaining <= 3) delay(remaining + 0.2)
    field = fieldAt(findEntry(vault, password, uuid, title, "show"), index, "totp")
  }
  if (field.totp_error || !field.totp_code) {
    throw new SetupError("error", "Could not generate the one-time code", "The TOTP secret in Enpass looks invalid")
  }
  return field.totp_code
}

// Asks for the master password; in dry-run mode (tests) the answer comes from the environment.
// Returns null when cancelled.
function askPassword(message) {
  if (config.dryRun) return envVar("enpass_test_answer")
  const app = Application.currentApplication()
  app.includeStandardAdditions = true
  try {
    app.activate()
    return app.displayDialog(message, {
      withTitle: "Enpass for Alfred",
      defaultAnswer: "",
      hiddenAnswer: true,
      buttons: ["Cancel", "Unlock"],
      defaultButton: "Unlock",
      cancelButton: "Cancel",
      withIcon: Path($.NSFileManager.defaultManager.currentDirectoryPath.js + "/icon.png"),
    }).textReturned
  } catch (e) {
    if (e.errorNumber === -128) return null
    throw e
  }
}

function setPassword() {
  const vault = loadVault()
  let message = "Enter the master password for your “" + vault.name + "” Enpass vault.\n\nIt’s stored in your macOS Keychain and only used to read the vault."
  for (let attempt = 0; attempt < 3; attempt++) {
    const password = askPassword(message)
    if (password === null) return silent()
    if (!password) {
      message = "The master password can’t be empty. Try again."
      continue
    }
    const check = exec(vault.cli, cliArgs(vault, "dryrun"), { env: { MASTERPW: password } })
    if (check.status !== 0) {
      const error = cliError(check)
      if (error.kind !== "badpassword") return notify(error.message, error.subtitle)
      message = "That master password didn’t unlock “" + vault.name + "”. Try again."
      continue
    }
    if (!savePassword(vault, password)) return notify("Could not save to the Keychain", "The master password was correct but couldn’t be stored")
    reopenSearch()
    return notify("Vault unlocked", "Master password saved in your Keychain")
  }
  return notify("Vault not unlocked", "The master password was wrong three times")
}

function reopenSearch() {
  if (config.dryRun) return
  Application("com.runningwithcrayons.Alfred").search(config.keyword + " ")
}

// Text or a URL from the Universal Action: search for the website's domain, or the text as is
function searchTerm(input) {
  const text = (input || "").trim()
  const host = hostOf(text)
  return (host || text).replace(/\s+/g, " ")
}

function act(input) {
  const action = envVar("action")
  const uuid = envVar("entry_uuid")
  const title = envVar("entry_title")
  const mode = envVar("mode", config.defaultAction) === "paste" ? "paste" : "copy"
  try {
    switch (action) {
      case "setpassword":
        return setPassword()
      case "forget": {
        const vault = loadVault()
        return deletePassword(vault)
          ? notify("Master password forgotten", "Removed from your Keychain")
          : notify("Nothing to forget", "No master password was saved for this vault")
      }
      case "configure":
        if (!config.dryRun) Application("com.runningwithcrayons.Alfred").revealWorkflow(config.bundleId, { configuration: true })
        return silent()
      case "open_enpass":
        if (!config.dryRun) Application(ENPASS_BUNDLE_ID).activate()
        return silent()
      case "back":
        reopenSearch()
        return silent()
      case "search":
        if (!config.dryRun) Application("com.runningwithcrayons.Alfred").search(config.keyword + " " + searchTerm(input))
        return silent()
      case "copy_text": {
        // Plain, non-secret text (e.g. the install command) goes to the clipboard normally
        const pasteboard = $.NSPasteboard.generalPasteboard
        pasteboard.clearContents
        pasteboard.setStringForType($(envVar("text")), $.NSPasteboardTypeString)
        return notify("Copied", envVar("text"))
      }
    }

    const { vault, password } = unlock()
    switch (action) {
      case "field": {
        const index = envVar("field_index")
        const type = envVar("field_type")
        if (type === "totp") return deliver(totpValue(vault, password, uuid, title, index), mode, "one-time code")
        // Non-secret fields come from `list`, so nothing is decrypted for them
        const secret = SECRET_TYPES.has(type) || envVar("field_secret") === "1"
        let field = fieldAt(findEntry(vault, password, uuid, title, secret ? "show" : "list"), index, type)
        if (!secret && isSecret(field)) field = fieldAt(findEntry(vault, password, uuid, title, "show"), index, type)
        if (!field.value) return notify(fieldLabel(field) + " is empty")
        return deliver(field.value, mode, fieldLabel(field).toLowerCase())
      }
      case "username": {
        const username = usernameOf(findEntry(vault, password, uuid, title, "list"))
        if (!username) return notify("No username")
        return deliver(username, mode, "username")
      }
      case "url":
        return openURL(urlOf(findEntry(vault, password, uuid, title, "list")))
      case "open_field": {
        const field = fieldAt(findEntry(vault, password, uuid, title, "list"), envVar("field_index"), "url")
        return openURL(normalizeURL(field.value || ""))
      }
      default:
        return notify("Unknown action", action || "(none)")
    }
  } catch (error) {
    if (!(error instanceof SetupError)) throw error
    if (error.kind === "setpassword" || error.kind === "badpassword") return setPassword()
    return notify(error.message, error.subtitle)
  }
}

// ─── Entry point ────────────────────────────────────────────────────────────

function run(argv) {
  const mode = argv[0]
  switch (mode) {
    case "list":
      return JSON.stringify(listEntries())
    case "fields":
      return JSON.stringify(listFields())
    case "act":
      return act(argv[1])
    case "clear":
      clearClipboard(argv[1])
      return ""
    default:
      return JSON.stringify({ items: [{ title: "Unknown mode: " + mode, valid: false }] })
  }
}
